version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username", "root", "--password", "root", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/?authSource=admin
    ports:
      - "8081:8081"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turnero-app
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      # Lo toma application.properties con mongodb.uri=${MONGODB_URI:...}
      MONGODB_URI: mongodb://root:root@mongo:27017/turnero?authSource=admin
      JAVA_OPTS: -XX:MaxRAMPercentage=75.0
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mongo_data:
